spring:
    application:
        name: user-service
    data:
        mongodb:
#            uri: mongodb+srv://akonakpevwe_db_user:Superboy8841@user-data.weqihkp.mongodb.net/userdb?appName=user-data
            uri: mongodb://localhost:27017/ecom_user
            database: ecom_user


server:
    port: 8082