spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: postgres
    #username: root
    #password: Superboy8841@
  #    url: jdbc:mysql://localhost:3306/productservice
#    url: jdbc:postgresql://ep-soft-frog-ay8cx1sn-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#    username: neondb_owner
#    password: npg_VxT9vuUg8cHb
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.mySQLDialect

server:
  port: 8081